### ISSUE TITLE
Can pdf-frame-vue use Chinese or other language? 

### ISSUE THREAD

**Issue by PoppingaLi** [I2Djs/pdf-frame#13]
I have tried using xxx.ttc of Chinese, but sadly it does not work. May someone give me some advices?

**Comment by nswamy14** [comment]
@PoppingaLi, I see an issue with loading collection fonts (.ttc and .dfont) in the current version. Use .ttf/.woff/.otf files if possible. We will address this issue in the next version soon.

Chinese Font example:  https://stackblitz.com/edit/pdf-frame-vuejs-xyoztz?file=src%2FApp.vue

**Comment by PoppingaLi** [comment]
<i-text
        :x="30"
        :y="150"
        :width="540"
        text="你好！" 
        :style="{
          fill: '#ffffff',
          textAlign: 'center',
          font: '15px Chinese',
        }"

“你好” means Hello
pdf preview can not display corretly. Can next version support font like browser? or utf-8 encoded?  at least this will support any language.

**Comment by nswamy14** [comment]
@PoppingaLi 
PDF-Frame internally uses pdfkit for pdf rendering. By default it supports just ASCII characters. For  non-Ascii characters, You need to use the right font file. I have created an example to showcase multi language support:

https://www.pdf-frame.org/?title=PDF:+Language+Fonts

let me know, if any questions.

**Comment by PoppingaLi** [comment]
@nswamy14 Great job! The font problem is solved. I have a slight question about "[Vue warn]: Failed to resolve component: i-path". Is there some steps about using package which I added not correctly?

**Comment by nswamy14** [comment]
@PoppingaLi , looks like you missed this config.
https://github.com/I2Djs/pdf-frame/wiki/pdf%E2%80%90frame%E2%80%90vue#config

This needs to be configured for Vue apps. For Nuxt applications, it is taken care of by the module.

**Comment by nswamy14** [comment]
Issue fixed as part of [v2.3.0](https://www.npmjs.com/package/@i2d/pdf-frame-vue) version
